#!/bin/bash

# bash_prompt
# http://bashrcgenerator.com
if [[ $HOSTNAME == eu-login* ]];
  then HN='euler-login'
elif [[ $HOSTNAME == staff-net-cx* ]];
  then HN='ethz.local'
elif [[ $HOSTNAME == staff-net-vpn* ]];
  then HN='ethz.vpn'
else
  HN=$HOSTNAME
fi

export PS1="\[\033[38;5;10m\]\u\[$(tput bold)\]\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[38;5;11m\]$HN\[$(tput bold)\]\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[38;5;9m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\] \\$\[$(tput sgr0)\] "
	
