#!/bin/bash

export VISUAL='mvim -f'   # Make MacVim the visual editor
export EDITOR="vim"   # Make vim the default editor

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# BASH COLORS
# LSCOLORS order: DIR, SYM_LINK, SOCKET, PIPE, EXE, BLOCK_SP
# CHAR_SP, EXE_SUID, EXE_GUID, DIR_STICKY, DIR_WO_STICKY
# a = black, b = red, c = green, d = brown, e = blue,
# f = magenta g = cyan, h = light gray, x = default
# lowercase is bold
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

MKL_NUM_THREADS=1
export MKL_NUM_THREADS

SSHAGENT=/usr/bin/ssh-agent
SSHAGENTARGS="-s"
if [ -z "$SSH_AUTH_SOCK" -a -x "$SSHAGENT" ]; then
	  eval `$SSHAGENT $SSHAGENTARGS`
	    trap "kill $SSH_AGENT_PID" 0
fi

#export GIT_EXTERNAL_DIFF=/Users/asoto/bin/gitdfdiff.sh

### BASH HISTORY ###
# Append history file rather then overwrite it
shopt -s histappend
# Don't put duplicate lines in history
export HISTCONTROL=ignoreboth
# Store 1000 commands in bash history
export HISTFILESIZE=1000
export HISTSIZE=1000
# Store when a command was used for the last time
export HISTTIMEFORMAT='%F %T '
# Ignore pwd history
export HISTIGNORE="pwd:history"
# Pull in any newly written lines, allowing to share history within active sessions
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
